/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicamentos;
import java.awt.event.ItemEvent;
import java.util.*;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTextField;

/**
 *
 * @author SP-DR
 */
public class AgregarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarProducto.class.getName());
    private int rol;
    private int idUsuario;
    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
    }
    
    public AgregarProducto(int rol, int idUsuario) {
        initComponents();
        txtCod_barras.requestFocus(true);
        getRootPane().setDefaultButton(btnAgregar);
        setLocationRelativeTo(null);
        this.rol = rol;
        this.idUsuario = idUsuario;
        setLocationRelativeTo(null);
        pack();
    }



    
    
    private void limpiarCampos() {
        txtCod_barras.setText("");
        txtNom_com.setText("");
        txtDescripcion.setText("");
        txtContenido.setText("");
        txtTipo.setText("");
        txtGramaje.setText("");
        txtFarmaceutica.setText("");
        txtPrecio_compra.setText("");
        txtPorcentajeV.setText("");
        txtFecha_cad.setText("");
        txtStock.setText("");
        txtMin_stock.setText("");
        txtMax_stock.setText("");
        txtPresentacion.setText("");

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtCod_barras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNom_com = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtGramaje = new javax.swing.JTextField();
        txtPrecio_compra = new javax.swing.JTextField();
        txtFecha_cad = new javax.swing.JTextField();
        txtPorcentajeV = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtMin_stock = new javax.swing.JTextField();
        txtMax_stock = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtPresentacion = new javax.swing.JTextField();
        txtFarmaceutica = new javax.swing.JTextField();
        txtContenido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agregar Producto");

        btnAgregar.setBackground(new java.awt.Color(51, 255, 51));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Codigo Barras");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Descripcion");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Gramaje");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Precio Compra");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("% Venta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Fecha Cad");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Stock");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Min Stock");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Max Stock");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Presentacion");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Tipo");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Contenido");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Farmaceutica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGramaje, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPrecio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPorcentajeV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCod_barras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNom_com, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(txtMin_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMax_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(txtFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod_barras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom_com, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGramaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentajeV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMin_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMax_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
            // Recolectar valores desde los JTextFields
            String codBarras = txtCod_barras.getText().trim();
            String nombre = txtNom_com.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            String contenido = txtContenido.getText().trim();
            String gramaje = txtGramaje.getText().trim();
            String presentacion = txtPresentacion.getText().trim();
            String farmaceutica = txtFarmaceutica.getText().trim();
            String tipo = txtTipo.getText().trim();

            String precioCompraStr = txtPrecio_compra.getText().trim();
            String porcentajeStr = txtPorcentajeV.getText().trim(); // obligatorio para calcular precio_venta

            String fechaCad = txtFecha_cad.getText().trim();
            String stockStr = txtStock.getText().trim();
            String minStockStr = txtMin_stock.getText().trim();
            String maxStockStr = txtMax_stock.getText().trim();

            // Validaciones iniciales
            if (codBarras.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El código de barras es obligatorio.");
                return;
            }
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre comercial es obligatorio.");
                return;
            }

            double precioCompra;
            double precioVenta;
            double porcentaje = 0.0;
            int stock, minStock, maxStock;

            // Parseo y validaciones numéricas
            try {
                if (precioCompraStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El precio de compra es obligatorio.");
                    return;
                }
                precioCompra = Double.parseDouble(precioCompraStr);
                if (precioCompra < 0) {
                    JOptionPane.showMessageDialog(this, "El precio de compra no puede ser negativo.");
                    return;
                }

                // Como txtPrecio_venta fue removido, requerimos porcentaje para calcular precio_venta.
                if (porcentajeStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debes indicar % Venta para calcular el Precio de Venta.");
                    return;
                }
                porcentaje = Double.parseDouble(porcentajeStr);
                if (porcentaje < 0) {
                    JOptionPane.showMessageDialog(this, "El porcentaje de venta no puede ser negativo.");
                    return;
                }

                // Calcular precio_venta a partir de precio_compra y porcentaje
                precioVenta = precioCompra * (1.0 + porcentaje / 100.0);
                precioVenta = Math.round(precioVenta * 100.0) / 100.0;

                // Stocks
                if (stockStr.isEmpty() || minStockStr.isEmpty() || maxStockStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Los campos de stock (Stock, Min, Max) son obligatorios.");
                    return;
                }
                stock = Integer.parseInt(stockStr);
                minStock = Integer.parseInt(minStockStr);
                maxStock = Integer.parseInt(maxStockStr);

                if (stock < 0 || minStock < 0 || maxStock < 0) {
                    JOptionPane.showMessageDialog(this, "Los valores de stock no pueden ser negativos.");
                    return;
                }
                if (minStock > maxStock) {
                    JOptionPane.showMessageDialog(this, "Min Stock no puede ser mayor que Max Stock.");
                    return;
                }
                if (stock < minStock || stock > maxStock) {
                    int opt = JOptionPane.showConfirmDialog(this,
                        "El Stock actual no está entre Min y Max. ¿Deseas continuar?",
                        "Stock fuera de rango",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                    if (opt != JOptionPane.YES_OPTION) return;
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Valores numéricos inválidos en precio, porcentaje o stock.");
                return;
            }

            Connection conn = null;
            PreparedStatement psCheck = null;
            ResultSet rsExist = null;

            try {
                conn = Conexion.conectar();

                // 1) Verificar si ya existe un producto con ese cod_barras
                String sqlCheck = "SELECT cod_barras, nom_com, activo FROM Productos WHERE cod_barras = ?";
                psCheck = conn.prepareStatement(sqlCheck);
                psCheck.setString(1, codBarras);
                rsExist = psCheck.executeQuery();

                if (rsExist.next()) {
                    boolean activo = rsExist.getInt("activo") == 1;
                    String nombreExistente = rsExist.getString("nom_com");
                    String estado = activo ? "activo" : "inactivo";

                    // Si está inactivo preguntamos si desea reactivar
                    if (!activo) {
                        int reactivar = JOptionPane.showConfirmDialog(
                            this,
                            "Se encontró el producto pero está inactivo:\n" +
                            "Nombre: " + nombreExistente + "\n\n" +
                            "¿Deseas reactivar este producto?",
                            "Producto inactivo",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE
                        );

                        if (reactivar == JOptionPane.YES_OPTION) {
                            // Reactivar: sólo actualizar activo = 1
                            String sqlReact = "UPDATE Productos SET activo = 1 WHERE cod_barras = ?";
                            try (PreparedStatement psReact = conn.prepareStatement(sqlReact)) {
                                psReact.setString(1, codBarras);
                                int updated = psReact.executeUpdate();
                                if (updated > 0) {
                                    JOptionPane.showMessageDialog(this, "Producto reactivado correctamente.");
                                    limpiarCampos();
                                } else {
                                    JOptionPane.showMessageDialog(this, "No se pudo reactivar el producto.");
                                }
                            }
                            return;
                        }
                        // Si no desea reactivar, preguntamos si quiere sobreescribir la info
                        int sobreescribir = JOptionPane.showConfirmDialog(
                            this,
                            "¿Deseas sobreescribir la información existente con los nuevos datos?",
                            "Sobreescribir producto",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE
                        );
                        if (sobreescribir != JOptionPane.YES_OPTION) {
                            JOptionPane.showMessageDialog(this, "Operación cancelada.");
                            return;
                        }
                        // Si acepta sobreescribir continuará con la actualización más abajo.
                    } else {
                        // Producto activo: preguntar si desea sobreescribir
                        int decision = JOptionPane.showConfirmDialog(
                            this,
                            "Ya existe un producto con ese código de barras:\n" +
                            "Nombre: " + nombreExistente + "\n" +
                            "Estado: " + estado + "\n\n" +
                            "¿Deseas sobrescribir la información con los nuevos datos?",
                            "Producto existente",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE
                        );

                        if (decision != JOptionPane.YES_OPTION) {
                            JOptionPane.showMessageDialog(this, "Operación cancelada.");
                            return;
                        }
                        // Si acepta sobrescribir continuará con la actualización más abajo.
                    }

                    // Llegamos aquí cuando el usuario eligió sobreescribir (o reactivar+sobreescribir flow)
                    String sqlUpdate = "UPDATE Productos SET " +
                        "nom_com = ?, descripcion = ?, contenido = ?, gramaje = ?, presentacion = ?, " +
                        "farmaceutica = ?, tipo = ?, precio_compra = ?, precio_venta = ?, porcentajeV = ?, " +
                        "fecha_cad = ?, stock = ?, min_stock = ?, max_stock = ?, activo = ? " +
                        "WHERE cod_barras = ?";

                    try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                        psUpdate.setString(1, nombre);
                        psUpdate.setString(2, descripcion.isEmpty() ? null : descripcion);
                        psUpdate.setString(3, contenido.isEmpty() ? null : contenido);
                        psUpdate.setString(4, gramaje.isEmpty() ? null : gramaje);
                        psUpdate.setString(5, presentacion.isEmpty() ? null : presentacion);
                        psUpdate.setString(6, farmaceutica.isEmpty() ? null : farmaceutica);
                        psUpdate.setString(7, tipo.isEmpty() ? null : tipo);
                        psUpdate.setDouble(8, precioCompra);
                        psUpdate.setDouble(9, precioVenta);      // calculado arriba
                        psUpdate.setDouble(10, porcentaje);      // guardamos porcentajeV
                        if (fechaCad == null || fechaCad.trim().isEmpty()) {
                            psUpdate.setNull(11, java.sql.Types.VARCHAR);
                        } else {
                            psUpdate.setString(11, fechaCad);
                        }
                        psUpdate.setInt(12, stock);
                        psUpdate.setInt(13, minStock);
                        psUpdate.setInt(14, maxStock);
                        psUpdate.setInt(15, 1); // activo = 1 (si sobreescribe se deja activo)
                        psUpdate.setString(16, codBarras); // WHERE cod_barras = ?

                        int filas = psUpdate.executeUpdate();
                        if (filas > 0) {
                            JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
                            limpiarCampos();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo actualizar el producto.");
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Error al actualizar producto: " + ex.getMessage());
                    }

                    return;
                }

                // 2) Si no existe, insertar nuevo producto
                String sqlInsert = "INSERT INTO Productos (" +
                    "cod_barras, nom_com, descripcion, contenido, gramaje, presentacion, farmaceutica, tipo, " +
                    "precio_compra, precio_venta, porcentajeV, fecha_cad, stock, min_stock, max_stock, activo" +
                    ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                    psInsert.setString(1, codBarras.isEmpty() ? null : codBarras);
                    psInsert.setString(2, nombre);
                    psInsert.setString(3, descripcion.isEmpty() ? null : descripcion);
                    psInsert.setString(4, contenido.isEmpty() ? null : contenido);
                    psInsert.setString(5, gramaje.isEmpty() ? null : gramaje);
                    psInsert.setString(6, presentacion.isEmpty() ? null : presentacion);
                    psInsert.setString(7, farmaceutica.isEmpty() ? null : farmaceutica);
                    psInsert.setString(8, tipo.isEmpty() ? null : tipo);
                    psInsert.setDouble(9, precioCompra);
                    psInsert.setDouble(10, precioVenta);   // calculado arriba
                    psInsert.setDouble(11, porcentaje);    // porcentajeV
                    if (fechaCad == null || fechaCad.trim().isEmpty()) {
                        psInsert.setNull(12, java.sql.Types.VARCHAR);
                    } else {
                        psInsert.setString(12, fechaCad);
                    }
                    psInsert.setInt(13, stock);
                    psInsert.setInt(14, minStock);
                    psInsert.setInt(15, maxStock);
                    psInsert.setInt(16, 1); // activo = 1

                    int filas = psInsert.executeUpdate();
                    if (filas > 0) {
                        JOptionPane.showMessageDialog(this, "Producto agregado con éxito.");
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo agregar el producto.");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error al insertar producto: " + ex.getMessage());
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al agregar/actualizar: " + e.getMessage());
                e.printStackTrace();
            } finally {
                try {
                    if (rsExist != null) rsExist.close();
                    if (psCheck != null) psCheck.close();
                    Conexion.cerrar(conn);
                } catch (SQLException ex) {
                    System.out.println("Error cerrando recursos: " + ex.getMessage());
                }
            }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuInventario menu = new MenuInventario(rol,idUsuario);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCod_barras;
    private javax.swing.JTextField txtContenido;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFarmaceutica;
    private javax.swing.JTextField txtFecha_cad;
    private javax.swing.JTextField txtGramaje;
    private javax.swing.JTextField txtMax_stock;
    private javax.swing.JTextField txtMin_stock;
    private javax.swing.JTextField txtNom_com;
    private javax.swing.JTextField txtPorcentajeV;
    private javax.swing.JTextField txtPrecio_compra;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
