/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicamentos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Bomby
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
    }
    
    private int rol;
    private int idUsuario;
    private String originalUser = null;
    public EditarUsuario(int rol, int idUsuario) {
        this.rol = rol;
        this.idUsuario = idUsuario;
        initComponents();
        setLocationRelativeTo(null);
        inicializar();
    }

    
     private void inicializar() {
        // Hacer combo editable para permitir que se modifique el nombre
        boxUser.setEditable(true);

        // Cargar usuarios desde la BD
        cargarUsuarios();

        // Al cambiar selección en el combo cargar la password del usuario seleccionado
        boxUser.addActionListener(evt -> {
            Object sel = boxUser.getSelectedItem();
            if (sel != null) {
                String nombre = sel.toString();
                // Si el item seleccionado está vacío no hacemos nada
                if (!nombre.trim().isEmpty()) {
                    cargarPasswordSeleccion(nombre);
                    originalUser = nombre; // recordamos el original para la actualización
                }
            }
        });

    }
     
     private void cargarUsuarios() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = Conexion.conectar();
            String sql = "SELECT nombre FROM Usuarios ORDER BY nombre COLLATE NOCASE ASC";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            boolean hay = false;
            while (rs.next()) {
                String nombre = rs.getString("nombre");
                model.addElement(nombre);
                hay = true;
            }
            boxUser.setModel(model);
            if (hay) {
                // seleccionar el primer elemento por defecto
                boxUser.setSelectedIndex(0);
                Object sel = boxUser.getSelectedItem();
                if (sel != null) {
                    originalUser = sel.toString();
                    cargarPasswordSeleccion(originalUser);
                }
            } else {
                originalUser = null;
                txtPassword.setText("");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
            } catch (SQLException ex) {
                System.out.println("Error cerrando recursos: " + ex.getMessage());
            }
            Conexion.cerrar(conn);
        }
    }
     
      private void cargarPasswordSeleccion(String nombre) {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = Conexion.conectar();
            String sql = "SELECT password FROM Usuarios WHERE nombre = ? LIMIT 1";
            ps = conn.prepareStatement(sql);
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            if (rs.next()) {
                String pass = rs.getString("password");
                txtPassword.setText(pass == null ? "" : pass);
            } else {
                txtPassword.setText("");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar contraseña: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
            } catch (SQLException ex) {
                System.out.println("Error cerrando recursos: " + ex.getMessage());
            }
            Conexion.cerrar(conn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boxUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Editar Usuario");

        boxUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        btnActualizar.setBackground(new java.awt.Color(0, 255, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(boxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxUser)
                    .addComponent(txtPassword))
                .addGap(29, 29, 29)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_Usuarios mu = new Menu_Usuarios(rol, idUsuario);
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         // Obtener nombre nuevo (soporta combo editable)
    String nuevoNombre;
    try {
        Object editorItem = boxUser.getEditor().getItem();
        nuevoNombre = editorItem == null ? "" : editorItem.toString().trim();
    } catch (Exception ex) {
        Object sel = boxUser.getSelectedItem();
        nuevoNombre = sel == null ? "" : sel.toString().trim();
    }

    String nuevaPass = txtPassword.getText() == null ? "" : txtPassword.getText().trim();

    if (originalUser == null || originalUser.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Primero selecciona un usuario existente para editar.");
        return;
    }
    if (nuevoNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre de usuario no puede estar vacío.");
        return;
    }
    if (nuevaPass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.");
        return;
    }

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        conn = Conexion.conectar();

        // 1) Verificar duplicados (case-insensitive), excluyendo el usuario original
        String sqlCheck = "SELECT COUNT(1) as cnt FROM Usuarios WHERE LOWER(nombre) = LOWER(?) AND nombre <> ?";
        ps = conn.prepareStatement(sqlCheck);
        ps.setString(1, nuevoNombre);
        ps.setString(2, originalUser);
        rs = ps.executeQuery();
        if (rs.next() && rs.getInt("cnt") > 0) {
            JOptionPane.showMessageDialog(this, "Ya existe otro usuario con ese nombre. Elige uno distinto.", "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        rs.close();
        ps.close();

        // 2) Actualizar registro usando el nombre original en WHERE
        String sqlUpdate = "UPDATE Usuarios SET nombre = ?, password = ? WHERE nombre = ?";
        ps = conn.prepareStatement(sqlUpdate);
        ps.setString(1, nuevoNombre);
        ps.setString(2, nuevaPass);
        ps.setString(3, originalUser);
        int filas = ps.executeUpdate();
        ps.close();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            // Si tienes un método para recargar el combo, llámalo (ej: cargarUsuarios())
            try {
                cargarUsuarios(); // si existe en tu clase
                boxUser.setSelectedItem(nuevoNombre);
                originalUser = nuevoNombre;
            } catch (Exception e) {
                // Si no existe cargarUsuarios(), al menos actualizar originalUser y combo
                originalUser = nuevoNombre;
                boxUser.setSelectedItem(nuevoNombre);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el usuario para actualizar o no hubo cambios.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try { if (rs != null) rs.close(); } catch (SQLException ex) { /* ignore */ }
        try { if (ps != null) ps.close(); } catch (SQLException ex) { /* ignore */ }
        Conexion.cerrar(conn);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxUser;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
